# Generated by Django 6.0 on 2026-04-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'food'), name='unique_cart_food'),
        ),
    ]
